/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;

/**
 *
 * @author ADV 123
 */
public class mainPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }
Color navcolor = new Color(153,51,255);
    Color headcolor = new Color(153,102,255);
    Color bodycolor = new Color(204,204,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        dashpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userpane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reportpane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addpane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        avail = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addpane1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        reportpane1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        accpane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();
        header = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(153, 51, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashpane.setBackground(new java.awt.Color(153, 51, 255));
        dashpane.setForeground(new java.awt.Color(255, 255, 255));
        dashpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpaneMouseExited(evt);
            }
        });
        dashpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        dashpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(dashpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 30));

        userpane.setBackground(new java.awt.Color(153, 51, 255));
        userpane.setForeground(new java.awt.Color(255, 255, 255));
        userpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpaneMouseExited(evt);
            }
        });
        userpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN PAGE");
        userpane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(userpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 30));

        reportpane.setBackground(new java.awt.Color(153, 51, 255));
        reportpane.setForeground(new java.awt.Color(255, 255, 255));
        reportpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportpaneMouseExited(evt);
            }
        });
        reportpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STOCK REPORT");
        reportpane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(reportpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        jLabel2.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C's INVENTORY");
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/violet-box-logo-web-online-shop-vector-23289931 (1).jpg"))); // NOI18N
        navbar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 240, 150));

        addpane.setBackground(new java.awt.Color(153, 51, 255));
        addpane.setForeground(new java.awt.Color(255, 255, 255));
        addpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addpaneMouseExited(evt);
            }
        });
        addpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADD PRODUCT");
        addpane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(addpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        avail.setBackground(new java.awt.Color(153, 51, 255));
        avail.setForeground(new java.awt.Color(255, 255, 255));
        avail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                availMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                availMouseExited(evt);
            }
        });
        avail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCT AVAILABLE");
        avail.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 30));

        navbar.add(avail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 30));

        addpane1.setBackground(new java.awt.Color(153, 51, 255));
        addpane1.setForeground(new java.awt.Color(255, 255, 255));
        addpane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addpane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addpane1MouseExited(evt);
            }
        });
        addpane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UPDATE INFO");
        addpane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(addpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, 30));

        reportpane1.setBackground(new java.awt.Color(153, 51, 255));
        reportpane1.setForeground(new java.awt.Color(255, 255, 255));
        reportpane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportpane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportpane1MouseExited(evt);
            }
        });
        reportpane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STOCK REPORT");
        reportpane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(reportpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        accpane.setBackground(new java.awt.Color(153, 51, 255));
        accpane.setForeground(new java.awt.Color(255, 255, 255));
        accpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accpaneMouseExited(evt);
            }
        });
        accpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ACCOUNT");
        accpane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        navbar.add(accpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 30));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 180, 490);

        maindesktop.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(190, 40, 600, 430);

        header.setBackground(new java.awt.Color(204, 51, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(header);
        header.setBounds(180, 0, 630, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dashboardPage1 up = new dashboardPage1();
        maindesktop.add(up).setVisible(true);
        //
    }//GEN-LAST:event_jLabel1MouseClicked

    private void dashpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseClicked
        dashboardPage1 db = new dashboardPage1();
        maindesktop.add(db).setVisible(true);

    }//GEN-LAST:event_dashpaneMouseClicked

    private void dashpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseEntered
        dashpane.setBackground(bodycolor);            // TODO add your handling code here:
    }//GEN-LAST:event_dashpaneMouseEntered

    private void dashpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseExited
        dashpane.setBackground(navcolor);
    }//GEN-LAST:event_dashpaneMouseExited

    private void userpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseClicked
        userPage up = new userPage();
        maindesktop.add(up).setVisible(true);

    }//GEN-LAST:event_userpaneMouseClicked

    private void userpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseEntered
        userpane.setBackground(bodycolor);
    }//GEN-LAST:event_userpaneMouseEntered

    private void userpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseExited
        userpane.setBackground(navcolor);
    }//GEN-LAST:event_userpaneMouseExited

    private void reportpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpaneMouseEntered
        reportpane.setBackground(bodycolor);
    }//GEN-LAST:event_reportpaneMouseEntered

    private void reportpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpaneMouseExited
        reportpane.setBackground(navcolor);
    }//GEN-LAST:event_reportpaneMouseExited

    private void addpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addpaneMouseClicked

    private void addpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpaneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addpaneMouseEntered

    private void addpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpaneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addpaneMouseExited

    private void availMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_availMouseClicked

    private void availMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_availMouseEntered

    private void availMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_availMouseExited

    private void addpane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addpane1MouseClicked

    private void addpane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpane1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addpane1MouseEntered

    private void addpane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpane1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addpane1MouseExited

    private void reportpane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpane1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reportpane1MouseEntered

    private void reportpane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpane1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reportpane1MouseExited

    private void accpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_accpaneMouseEntered

    private void accpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_accpaneMouseExited

    private void accpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseClicked
accPage ap = new accPage ();
        ap.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_accpaneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accpane;
    private javax.swing.JPanel addpane;
    private javax.swing.JPanel addpane1;
    private javax.swing.JPanel avail;
    private javax.swing.JPanel dashpane;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel reportpane;
    private javax.swing.JPanel reportpane1;
    private javax.swing.JPanel userpane;
    // End of variables declaration//GEN-END:variables
}
